class_name CharacterTextureBox
extends AspectRatioContainer

@export var body: TextureRect
@export var eyes: TextureRect

@export var parts: Dictionary[Character.Slot, TextureRect]

## auto generated by connecting in the editor
func _on_skin_color_button_color_changed(color: Color) -> void:
	body.self_modulate = color

func _on_eye_color_button_color_changed(color: Color) -> void:
	eyes.self_modulate = color

func display(character: Character) -> void:
	body.self_modulate = character.skin_color
	eyes.self_modulate = character.eye_color
	for part in character.parts:
		_apply_part(character.parts[part])

func _apply_part(part: CharacterPart) -> void:
	assert(part != null)
	var slot_node: TextureRect = parts.get(part.slot)
	assert(slot_node != null)
	if part.texture == null:
		slot_node.visible = false
	else:
		slot_node.visible = true
		slot_node.texture = part.texture
		slot_node.self_modulate = part.defaultColor
